[package]
name = "indicatif"
description = "A progress bar and cli reporting library for Rust"
version = "0.15.0"
keywords = ["cli", "progress", "pb", "colors", "progressbar"]
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
license = "MIT"
repository = "https://github.com/mitsuhiko/indicatif"
documentation = "https://docs.rs/indicatif"
readme = "README.md"
edition = "2018"
exclude = ["screenshots/*"]

[dependencies]
regex = { version = "1.3.1", default-features = false, features = ["std"], optional = true }
lazy_static = "1.0"
number_prefix = "0.3"
console = { version = ">=0.9.1, <1.0.0", default-features = false }
unicode-segmentation = { version = "1.6.0", optional = true }
unicode-width = { version = "0.1.7", optional = true }
rayon = { version = "1.0", optional = true }

[dev-dependencies]
rand = "0.7.0"
tokio = { version = "0.2.18", features = ["time"] }

[features]
default = ["template"]
improved_unicode = ["unicode-segmentation", "unicode-width", "console/unicode-width"]
template = ["regex"]

# Legacy alias for `rayon`
with_rayon = ["rayon"]
